### ISSUE TITLE
Map/getSingle

### ISSUE THREAD

**Issue by Jhadkin** [arupiot/Desk-Check-Backend#11]
Floor, building

**Comment by Exilliar** [comment]
This might end up being just some geojson files rather than images, so hold off on completing this issue until after a decision has been made on that.

**Comment by Exilliar** [comment]
@Jhadkin 

1. create a folder in the project to store json files
2. create a new context thing for the /map endpoint
3. create the endpoing map/getSingle which will take in floor number and then give the right json file (I will find the other json files soon)
